/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file.
 *
 * =>  @see ./src/schemas/errors/validationError.json
 *
 * and run "npm run schema-to-interface" to regenerate this file.
 */

export interface ValidationError {
  errors?: {
    location?: string;
    msg?: string;
    param?: string;
    value?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
