/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file.
 *
 * =>  @see ./src/schemas/events/Event.yml
 *
 * and run "npm run schema-to-interface" to regenerate this file.
 */

export interface Event {
  "@context"?: "kulturdaten.berlin/api/v1/spec";
  "@type"?: "Event";
  identifier?: string;
  title?: Text;
  subTitle?: Text;
  description?: Description;
  visibility?: "published" | "unpublished" | "draft" | "archived" | "restricted";
  origin?: string;
  eventStatus?: "cancelled" | "postponed" | "rescheduled" | "scheduled";
  eventAttendanceMode?: "offline" | "online" | "mixed";
  location?: Location;
  images?: string[];
}
export interface Text {
  de?: string;
  en?: string;
  "de-easy"?: string;
  [k: string]: unknown;
}
export interface Description {
  de?: string;
  en?: string;
  "de-easy"?: string;
  [k: string]: unknown;
}
export interface Location {
  name?: {
    [k: string]: unknown;
  };
}
