/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file.
 *
 * =>  @see ./src/schemas/events/Event.yml
 *
 * and run "npm run schema-to-interface" or "npm run generate" to regenerate this file.
 */

export type Event = Core & {
  "@type"?: "Event" | "EventSeries" | "ExhibitionEvent";
  kind?: "culture";
  origin?: string;
  title?: Title;
  subTitle?: SubTitle;
  description?: Description;
  shortDescription?: Description;
  startDate?: string;
  endDate?: string;
  previousStartDate?: string;
  doorTime?: string;
  typicalAgeRange?: string;
  categories?: string[];
  keywords?: string[];
  inLanguages?: string[];
  isAccessibleForFree?: boolean;
  sameAs?: string;
  visibility?: "published" | "unpublished" | "draft" | "archived" | "restricted";
  eventStatus?: "cancelled" | "postponed" | "rescheduled" | "scheduled";
  eventAttendanceMode?: "offline" | "online" | "mixed";
  location?: Location;
  organizer?: Organization;
  subEvents?: Event[];
  superEvent?: string;
};

export interface Core {
  "@context"?: "kulturdaten.berlin/api/v1/spec";
  identifier?: string;
  created?: string;
  updated?: string;
}
export interface Title {
  de?: string;
  en?: string;
  "de-easy"?: string;
  [k: string]: unknown;
}
export interface SubTitle {
  de?: string;
  en?: string;
  "de-easy"?: string;
  [k: string]: unknown;
}
export interface Description {
  de?: string;
  en?: string;
  "de-easy"?: string;
  [k: string]: unknown;
}
export interface Location {
  name?: {
    [k: string]: unknown;
  };
}
export interface Organization {
  identifier: string;
  name: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}
