/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file.
 *
 * =>  @see ./src/schemas/media/ImageObject.yml
 *
 * and run "npm run schema-to-interface" or "npm run generate" to regenerate this file.
 */

export type ImageObject = Core & {
  "@type"?: "ImageObject";
  contentUrl?: string;
  height?: number;
  width?: number;
  caption?: SubTitle;
  description?: Description;
  encodingFormat?: string;
  sha256?: string;
  license?: string;
  acquireLicensePage?: string;
};

export interface Core {
  "@context"?: "kulturdaten.berlin/api/v1/spec";
  identifier?: string;
  created?: string;
  updated?: string;
}
export interface SubTitle {
  de?: string;
  en?: string;
  "de-easy"?: string;
  [k: string]: unknown;
}
export interface Description {
  de?: string;
  en?: string;
  "de-easy"?: string;
  [k: string]: unknown;
}
