/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file.
 *
 * =>  @see ./src/schemas/locations/Location.yml
 *
 * and run "npm run schema-to-interface" to regenerate this file.
 */

export interface Location {
  name?: {
    [k: string]: unknown;
  };
}
