/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file.
 *
 * =>  @see ./src/schemas/ImageObject.yml
 *
 * and run "npm run schema-to-interface" or "npm run generate" to regenerate this file.
 */

import {Core} from "./Core.generated";
import {SubTitle} from "./SubTitle.generated";
import {Description} from "./Description.generated";

export type ImageObject = Core & {
  "@type"?: "ImageObject";
  contentUrl?: string;
  height?: number;
  width?: number;
  caption?: SubTitle;
  description?: Description;
  encodingFormat?: string;
  sha256?: string;
  license?: string;
  acquireLicensePage?: string;
};
