import { writeFileSync } from 'fs'
import { compileFromFile } from 'json-schema-to-typescript'

async function generate() {

	generateInterface('organizers/organizer', 'organizers/models/organizer');
	generateInterface('organizers/createOrganizer', 'organizers/dtos/create.organizer.dto');
	generateInterface('organizers/patchOrganizer', 'organizers/dtos/patch.organizer.dto');

	generateInterface('users/user', 'users/models/user');
	generateInterface('users/createUser', 'users/dtos/create.user.dto');
	generateInterface('users/patchUser', 'users/dtos/patch.user.dto');

	generateInterface('auth/auth', 'auth/dtos/auth');
	generateInterface('auth/login', 'auth/dtos/login');

	generateInterface('health/health', 'health/dtos');

	generateInterface('errors/notFoundError', 'common/errors/notFoundError');
	generateInterface('errors/validationError', 'common/errors/validationError');

	
}

async function generateInterface(schemaFile: string, targetFile: string) {
	
	const options = (baseFile: string) => {
		return {
			bannerComment: `/* eslint-disable */
		/**
		 * This file was automatically generated by json-schema-to-typescript.
		 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file.
		 * 
		 * =>  @see ${baseFile}
		 * 
		 * and run "npm run schema-to-interface" to regenerate this file.
		 */
		`
		}
	};
	const schemaPath = `./src/schemas/${schemaFile}.json`;
	const targetPath = `./src/${targetFile}.generated.ts`;

	writeFileSync(targetPath, await compileFromFile(schemaPath, options(schemaPath)))	
}

generate();