import { writeFileSync } from 'fs'
import { compileFromFile } from 'json-schema-to-typescript'

async function generate() {

	generateInterface('organizer', 'organizers/organizer');
	generateInterface('createOrganizer', 'organizers/dtos/create.organizer.dto');

	generateInterface('auth', 'auth/dtos/auth');
	generateInterface('login', 'auth/dtos/login');

	generateInterface('notFoundError', 'common/errors/notFoundError');

	
}

async function generateInterface(schemaFile: string, targetFile: string) {
	
	const options = (baseFile: string) => {
		return {
			bannerComment: `/* eslint-disable */
		/**
		 * This file was automatically generated by json-schema-to-typescript.
		 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file.
		 * 
		 * =>  @see ${baseFile}
		 * 
		 * and run "npm run schema-to-interface" to regenerate this file.
		 */
		`
		}
	};
	const schemaPath = `./src/schemas/${schemaFile}.json`;
	const targetPath = `./src/${targetFile}.generated.ts`;

	writeFileSync(targetPath, await compileFromFile(schemaPath, options(schemaPath)))	
}

generate();