openapi: '3.0.2'
info:
  title: API Kulturdaten.Berlin 
  version: '1.0.0'
servers:
  - url: http://localhost:3000/v1/
paths:

  /auth/token:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: auth/login.json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: auth/auth.json      

  /organizations:
    get:
      tags:
        - Organizations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  organizations: 
                    type: array
                    items:    
                      $ref: organizations/organization.json
  
    post:
      tags:
        - Organizations
      requestBody:
        content:
          application/json:
            schema:
              $ref: organizations/createOrganization.json
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier: 
                    type: string


  /organizations/{identifier}:
    parameters:
      - in: path
        name: identifier 
        required: true
        schema:
          type: string
        description: The organization ID
    get:
      tags:
        - Organizations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  organization: 
                    $ref: organizations/organization.json
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/notFoundError.json
    patch:
      tags:
        - Organizations
      requestBody:
        content:
          application/json:
            schema:
              $ref: organizations/patchOrganization.json
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/notFoundError.json
    delete:
      tags:
        - Organizations
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/notFoundError.json

  /users:
    get:
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users: 
                    type: array
                    items:    
                      $ref: users/user.json
    post:
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: users/createUser.json
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier: 
                    type: string
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: errors/emailAlreadyInUseError.json

  /users/{identifier}:
    parameters:
      - in: path
        name: identifier 
        required: true
        schema:
          type: string
        description: The user ID
    get:
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: users/user.json
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/notFoundError.json
    patch:
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: users/patchUser.json
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/notFoundError.json
    delete:
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/notFoundError.json



  /health:
    get:
      tags:
        - Server
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: health/health.json

components:
  securitySchemes:
    bearerAuth:           
      type: http
      scheme: bearer
      bearerFormat: JWT   