openapi: '3.0.2'
info:
  title: API Kulturdaten.Berlin 
  version: '1.0.0'
servers:
  - url: http://localhost:3000/v1/
paths:

  /auth/token:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: auth/Login.yml
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: auth/Auth.yml      

  /organizations:
    get:
      tags:
        - Organizations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  organizations: 
                    type: array
                    items:    
                      $ref: organizations/Organization.yml
  
    post:
      tags:
        - Organizations
      requestBody:
        content:
          application/json:
            schema:
              $ref: organizations/CreateOrganization.yml
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier: 
                    type: string


  /organizations/{identifier}:
    parameters:
      - in: path
        name: identifier 
        required: true
        schema:
          type: string
        description: The organization ID
    get:
      tags:
        - Organizations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  organization: 
                    $ref: organizations/Organization.yml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/NotFoundError.yml
    patch:
      tags:
        - Organizations
      requestBody:
        content:
          application/json:
            schema:
              $ref: organizations/PatchOrganization.yml
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/NotFoundError.yml
    delete:
      tags:
        - Organizations
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/NotFoundError.yml

  /users:
    get:
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users: 
                    type: array
                    items:    
                      $ref: users/User.yml
    post:
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: users/CreateUser.yml
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier: 
                    type: string
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: errors/EmailAlreadyInUseError.yml

  /users/{identifier}:
    parameters:
      - in: path
        name: identifier 
        required: true
        schema:
          type: string
        description: The user ID
    get:
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: users/User.yml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/NotFoundError.yml
    patch:
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: users/PatchUser.yml
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/NotFoundError.yml
    delete:
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: errors/NotFoundError.yml



  /health:
    get:
      tags:
        - Server
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: health/Health.yml

  /events:
    get:
      tags:
        - Server
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: events/Event.yml

components:
  securitySchemes:
    bearerAuth:           
      type: http
      scheme: bearer
      bearerFormat: JWT   

  schemas:
    Login:
      $ref: auth/Login.yml

    Auth:
      $ref: auth/Auth.yml 
    
    Organization:
      $ref: organizations/Organization.yml

    CreateOrganization:
      $ref: organizations/CreateOrganization.yml

    PatchOrganization:
      $ref: organizations/PatchOrganization.yml

    User:
      $ref: users/User.yml
    
    CreateUser:
      $ref: users/CreateUser.yml
    
    PatchUser:
      $ref: users/PatchUser.yml

    Health:
      $ref: health/Health.yml

    ResourceNotFoundError:
      $ref: errors/NotFoundError.yml
    
    EmailAlreadyInUseError:
      $ref: errors/EmailAlreadyInUseError.yml