openapi: '3.0.2'
info:
  title: API Kulturdaten.Berlin 
  version: '1.0.0'
servers:
  - url: http://localhost:3000/v1/
paths:

  /auth/token:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'      

  /events:
    get:
      tags:
        - Events
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  events: 
                    type: array
                    items:    
                      $ref: '#/components/schemas/Event'

  /organizations:
    get:
      tags:
        - Organizations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  organizations: 
                    type: array
                    items:    
                      $ref: '#/components/schemas/Organization'  
  
    post:
      tags:
        - Organizations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrganization'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier: 
                    type: string


  /organizations/{identifier}:
    parameters:
      - in: path
        name: identifier 
        required: true
        schema:
          type: string
        description: The organization ID
    get:
      tags:
        - Organizations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  organization: 
                    $ref: '#/components/schemas/Organization'  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
    patch:
      tags:
        - Organizations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchOrganization'
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
    delete:
      tags:
        - Organizations
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'

  /users:
    get:
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users: 
                    type: array
                    items:    
                      $ref: '#/components/schemas/User'
    post:
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier: 
                    type: string
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailAlreadyInUseError'

  /users/{identifier}:
    parameters:
      - in: path
        name: identifier 
        required: true
        schema:
          type: string
        description: The user ID
    get:
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
    patch:
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchUser'
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
    delete:
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '204':
          description: OK  
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'



  /health:
    get:
      tags:
        - Server
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'



components:
  securitySchemes:
    bearerAuth:           
      type: http
      scheme: bearer
      bearerFormat: JWT   

  schemas:
    Login:
      $ref: models/Login.yml

    Auth:
      $ref: models/Auth.yml 
    
    Organization:
      $ref: models/Organization.yml

    CreateOrganization:
      $ref: models/CreateOrganization.yml

    PatchOrganization:
      $ref: models/PatchOrganization.yml

    User:
      $ref: models/User.yml
    
    CreateUser:
      $ref: models/CreateUser.yml
    
    PatchUser:
      $ref: models/PatchUser.yml

    Health:
      $ref: models/Health.yml

    NotFoundError:
      $ref: models/NotFoundError.yml
    
    EmailAlreadyInUseError:
      $ref: models/EmailAlreadyInUseError.yml

    Event:
       $ref: models/Event.yml
