name: Linter & TypeScript

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linter-and-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Generate OpenAPI schema files
        run: npm run generate
      - name: Run ESLint
        run: npm run lint
      - name: Run TypeScript compiler
        run: npm run typecheck
      - name: Lint OpenAPI file
        run: npm run lint-openapi
